"""Render the memo as Markdown. The metrics table comes from code, never from the model."""
from __future__ import annotations

from .agents import Claim, Memo
from .evidence import EvidencePack, Excerpt, Fact
from .verify import GroundingReport

KEY_TABLE = ["Revenue", "Revenue growth (YoY)", "Revenue CAGR (3-yr)", "Gross margin", "Operating margin",
             "Net margin", "Free cash flow", "FCF margin", "Net debt (LT debt - cash)", "Return on equity",
             "Diluted share count change (YoY)"]


def _cite(c: Claim) -> str:
    return f"{c.text} <sub>{' '.join(f'[{x}]' for x in c.citations)}</sub>"


def render(memo: Memo, pack: EvidencePack, report: GroundingReport, model: str) -> str:
    latest: dict[str, Fact] = {}
    for f in pack.facts:
        if f.label in KEY_TABLE and (f.label not in latest or f.period >= latest[f.label].period):
            latest[f.label] = f

    out = [
        f"# {memo.company} ({memo.ticker}): due-diligence memo",
        "",
        f"**Verdict: {memo.verdict}.** {_cite(memo.verdict_rationale)}",
        "",
        "> Research triage generated by an AI agent team from the company's latest 10-K. "
        "Not investment advice. Every claim is cited and machine-checked against the filing; see the grounding report.",
        "",
        f"Source: [latest 10-K]({memo.filing_url}) · Model: `{model}`",
        "",
        "## Thesis",
        "",
        _cite(memo.thesis),
        "",
        "## Key metrics",
        "",
        "| Metric | Value | FY end | Evidence |",
        "|---|---|---|---|",
    ]
    for label in KEY_TABLE:
        if label in latest:
            f = latest[label]
            out.append(f"| {label} | {f.display()} | {f.period} | [{f.id}] |")
    out += ["", "## Bull case", ""] + [f"- {_cite(c)}" for c in memo.bull]
    out += ["", "## Bear case (after red-team review)", ""] + [f"- {_cite(c)}" for c in memo.bear]
    if memo.objections:
        out += ["", "<details><summary>All red-team objections that passed verification</summary>", ""]
        out += [f"- **{c.severity or 'n/a'}**: {_cite(c)}" for c in memo.objections]
        out += ["", "</details>"]
    out += ["", "## Diligence questions for a human", ""] + [f"{i}. {q}" for i, q in enumerate(memo.questions, 1)]

    out += ["", "## Grounding report", "",
            f"{report.kept} of {report.proposed} claims proposed by the agents passed verification "
            f"({report.rate:.0%}). Dropped claims never reached downstream agents or this memo.", ""]
    if report.dropped:
        out += ["| Stage | Dropped claim | Reason |", "|---|---|---|"]
        for d in report.dropped:
            out.append(f"| {d['stage']} | {d['claim'][:160].replace('|', '/')} | {d['reason'].replace('|', '/')} |")

    used = sorted({x for c in _all_claims(memo) for x in c.citations} | {latest[k].id for k in latest},
                  key=lambda s: (s[0], int(s[1:])))
    out += ["", "## Evidence cited", ""]
    for id_ in used:
        item = pack.get(id_)
        if isinstance(item, Fact):
            out.append(f"- **[{id_}]** {item.label}, FY ending {item.period}: {item.display()} · `{item.source}`")
        elif isinstance(item, Excerpt):
            snippet = item.text if len(item.text) <= 400 else item.text[:400] + "…"
            out.append(f"- **[{id_}]** *{item.section}*: \"{snippet}\"")
    return "\n".join(out) + "\n"


def _all_claims(m: Memo) -> list[Claim]:
    return [m.thesis, m.verdict_rationale, *m.bull, *m.bear, *m.objections]
