"""Render the memo as Markdown. The metrics table and the scorecard come from code, never from the model."""
from __future__ import annotations

import re
from datetime import date

from .agents import Claim, Memo
from .evidence import EvidencePack, Excerpt, Fact
from .verify import GroundingReport

KEY_TABLE = ["Revenue", "Revenue growth (YoY)", "Revenue CAGR (3-yr)", "Gross margin", "Operating margin",
             "Net margin", "Free cash flow", "FCF margin", "Net debt (LT debt - cash)", "Return on equity",
             "Diluted share count change (YoY)"]
VALUATION = ["Market cap", "P/E (market cap / net income)", "P/FCF", "FCF yield", "EV / revenue"]


def _cite(c: Claim) -> str:
    return f"{c.text} <sub>{' '.join(f'[{x}]' for x in c.citations)}</sub>"


def _latest(pack: EvidencePack, labels: list[str]) -> dict[str, Fact]:
    out: dict[str, Fact] = {}
    for f in pack.facts:
        if f.label in labels and (f.label not in out or f.period >= out[f.label].period):
            out[f.label] = f
    return out


def render(memo: Memo, pack: EvidencePack, report: GroundingReport, model: str) -> str:
    sc = memo.scorecard
    latest = _latest(pack, KEY_TABLE)
    val = _latest(pack, VALUATION)
    verdict = sc.verdict if sc else memo.verdict

    out = [
        f"# {memo.company} ({memo.ticker}): due-diligence memo",
        "",
        f"**Verdict: {verdict}**" + (f" (scorecard {sc.points:g}/{sc.possible}, {sc.pct:.0%})" if sc else "")
        + f" · PM's own view: {memo.verdict}",
        "",
        "> Research triage generated by an AI agent team from the company's latest 10-K and cited web research. "
        "Not investment advice. Every claim is cited and machine-checked against its source; see the grounding report.",
        "",
        f"Source: [latest 10-K]({memo.filing_url}) · Generated {date.today().isoformat()} · Model: `{model}`",
        "",
        "## Thesis",
        "",
        _cite(memo.thesis),
    ]
    if memo.verdict_rationale.text != memo.thesis.text:
        out += ["", f"**PM's rationale:** {_cite(memo.verdict_rationale)}"]

    if sc:
        out += ["", "## Scorecard", "",
                "The verdict comes from this rubric, computed in code from the evidence. It is not the model's opinion.", "",
                "| Dimension | Score | Basis | Evidence |", "|---|---|---|---|"]
        for ln in sc.lines:
            s = "n/a" if ln.score is None else f"{ln.score}/2"
            out.append(f"| {ln.dimension} | {s} | {ln.basis} | {' '.join(f'[{i}]' for i in ln.fact_ids)} |")
        out.append(f"| Red-team penalty | −{sc.penalty:g} | {sc.penalty_basis} | |")
        out.append(f"| **Total** | **{sc.points:g}/{sc.possible}** | Dig deeper ≥65% · Watch ≥40% · Pass <40% | |")

    out += ["", "## Key metrics", "", "| Metric | Value | Period | Evidence |", "|---|---|---|---|"]
    for label in KEY_TABLE:
        if label in latest:
            f = latest[label]
            out.append(f"| {label} | {f.display()} | FY ending {f.period} | [{f.id}] |")
    for label in VALUATION:
        if label in val:
            f = val[label]
            out.append(f"| {label} | {f.display()} | as of {f.period} | [{f.id}] |")

    out += ["", "## Bull case", ""] + [f"- {_cite(c)}" for c in memo.bull]
    out += ["", "## Bear case (after red-team review)", ""] + [f"- {_cite(c)}" for c in memo.bear]
    if memo.objections:
        out += ["", "<details><summary>All red-team objections that passed verification</summary>", ""]
        out += [f"- **{c.severity or 'n/a'}**: {_cite(c)}" for c in memo.objections]
        out += ["", "</details>"]

    if memo.research:
        answered = [r for r in memo.research if r.claims]
        open_qs = [r for r in memo.research if not r.claims]
        out += ["", "## Diligence questions", "",
                f"The PM raised {len(memo.research)} questions. The research agent answered {len(answered)} from "
                f"cited public sources, and {len(open_qs)} remain for a human.", ""]
        for r in answered:
            out += [f"**Q: {r.question}**", ""] + [f"- {_cite(c)}" for c in r.claims] + [""]
        if open_qs:
            out += ["**Still open (needs a human):**", ""]
            out += [f"- {r.question} *({r.unanswered})*" for r in open_qs]
    else:
        out += ["", "## Diligence questions", ""] + [f"{i}. {q}" for i, q in enumerate(memo.questions, 1)]

    out += ["", "## Grounding report", "",
            f"{report.kept} of {report.proposed} claims proposed by the agents passed verification "
            f"({report.rate:.0%}). Dropped claims never reached downstream agents or this memo.", ""]
    if report.dropped:
        out += ["| Stage | Dropped claim | Reason |", "|---|---|---|"]
        for d in report.dropped:
            out.append(f"| {d['stage']} | {d['claim'][:160].replace('|', '/')} | {d['reason'].replace('|', '/')} |")

    cited = {x for c in _all_claims(memo) for x in c.citations}
    cited |= {f.id for f in (*latest.values(), *val.values())}
    if sc:
        cited |= {i for ln in sc.lines for i in ln.fact_ids}
    for id_ in list(cited):  # a web-sourced fact (market cap) brings its W-excerpts along
        f = pack.get(id_)
        if isinstance(f, Fact) and f.source.startswith("web:"):
            cited |= set(re.findall(r"W\d+", f.source))
    used = sorted(cited, key=lambda s: (s[0], int(s[1:])))
    out += ["", "## Evidence cited", ""]
    for id_ in used:
        item = pack.get(id_)
        if isinstance(item, Fact):
            out.append(f"- **[{id_}]** {item.label} ({item.period}): {item.display()} · `{item.source}`")
        elif isinstance(item, Excerpt):
            snippet = item.text if len(item.text) <= 400 else item.text[:400] + "…"
            where = f"[{item.title or item.url}]({item.url})" if item.url else f"*{item.section}*"
            out.append(f"- **[{id_}]** {where}: \"{snippet}\"")
    return "\n".join(out) + "\n"


def _all_claims(m: Memo) -> list[Claim]:
    research = [c for r in m.research for c in r.claims]
    return [m.thesis, m.verdict_rationale, *m.bull, *m.bear, *m.objections, *research]
